### PR TITLE
Bug Fixes (Steam Offers, Auto-Delist)

### PR DESCRIPTION
**Pull request by gustavo-dev**
A simple way to fix the "sent" Offer, when Steam Services are unavailable.

### CODE REVIEW

**Comment by Cohucohu** [comment]
the auto delist not working when price drops. Please take action

**Comment by gustavo-dev** [comment]
@Cohucohu can you create a new issue regarding this problem, so we can take a look at it?

**Comment by gustavo-dev** [comment]
I went ahead and made a few more commits that were not really in the scope of this pull request (that was supposed to be around Steam offers), but I took the liberty to do them and therefore I'm changing the title of it. It is worth mentioning that I haven't tested those changes given the fact that I made them on my cellphone. However, I think those changes should work and fix the problems presented here.

**Comment by antal-k** [comment]
Thank you @gustavo-dev

**Comment by gustavo-dev** [comment]
No problem @antal-k . Btw there's actually a problem in one commit where I forgot to multiply the percentage change by -1, so the item doesn't get delisted when the price increases, but when it decreases. I'll create a commit right now. Sorry for that.

**Pull request merged**
